// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaMNxIUIH2mcBYSO-HGVIVdlEXC-7RVVc',
    appId: '1:650819260381:web:2aa1bdd4c6ba5080217034',
    messagingSenderId: '650819260381',
    projectId: 'moviesapp-eae42',
    authDomain: 'moviesapp-eae42.firebaseapp.com',
    storageBucket: 'moviesapp-eae42.appspot.com',
    measurementId: 'G-8X4HGZLST3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYZL5QLz2fGOLc8Y7qIC-dYVQP3Z0X63A',
    appId: '1:650819260381:android:0388bf1169b03a75217034',
    messagingSenderId: '650819260381',
    projectId: 'moviesapp-eae42',
    storageBucket: 'moviesapp-eae42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-51I1K-A4ozTW6d9Snp76ZKHBSZ1w2UM',
    appId: '1:650819260381:ios:ba164585dbcb7a19217034',
    messagingSenderId: '650819260381',
    projectId: 'moviesapp-eae42',
    storageBucket: 'moviesapp-eae42.appspot.com',
    iosClientId: '650819260381-rjoi0bv6dlc0u2l3j49lk9vmre3l694h.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-51I1K-A4ozTW6d9Snp76ZKHBSZ1w2UM',
    appId: '1:650819260381:ios:ba164585dbcb7a19217034',
    messagingSenderId: '650819260381',
    projectId: 'moviesapp-eae42',
    storageBucket: 'moviesapp-eae42.appspot.com',
    iosClientId: '650819260381-rjoi0bv6dlc0u2l3j49lk9vmre3l694h.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
